package com.mmt.vhr.model;

import java.util.ArrayList;
import java.util.List;

public class Department {
    private List<Department> children = new ArrayList<>();

    private Integer result;

    public Integer getResult() {
        return result;
    }

    public void setResult(Integer result) {
        this.result = result;
    }

    public List<Department> getChildren() {
        return children;
    }

    public void setChildren(List<Department> children) {
        this.children = children;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.id
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.name
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.parentId
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    private Integer parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.depPath
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    private String depPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.enabled
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    private Boolean enabled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.isParent
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    private Boolean isParent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.id
     *
     * @return the value of department.id
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.id
     *
     * @param id the value for department.id
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.name
     *
     * @return the value of department.name
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.name
     *
     * @param name the value for department.name
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.parentId
     *
     * @return the value of department.parentId
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.parentId
     *
     * @param parentId the value for department.parentId
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.depPath
     *
     * @return the value of department.depPath
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    public String getDepPath() {
        return depPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.depPath
     *
     * @param depPath the value for department.depPath
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    public void setDepPath(String depPath) {
        this.depPath = depPath == null ? null : depPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.enabled
     *
     * @return the value of department.enabled
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    public Boolean getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.enabled
     *
     * @param enabled the value for department.enabled
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.isParent
     *
     * @return the value of department.isParent
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    public Boolean getIsParent() {
        return isParent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.isParent
     *
     * @param isParent the value for department.isParent
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    public void setIsParent(Boolean isParent) {
        this.isParent = isParent;
    }
}