package com.mmt.vhr.model;

import com.fasterxml.jackson.annotation.JsonIgnore;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.authority.SimpleGrantedAuthority;
import org.springframework.security.core.userdetails.UserDetails;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

public class Hr implements UserDetails {
    private List<Role> roles;

    public List<Role> getRoles() {
        return roles;
    }

    public void setRoles(List<Role> roles) {
        this.roles = roles;
    }


    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr.id
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr.name
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr.phone
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr.telephone
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    private String telephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr.address
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr.enabled
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    private Boolean enabled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr.username
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr.password
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr.userface
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    private String userface;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr.remark
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr.id
     *
     * @return the value of hr.id
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr.id
     *
     * @param id the value for hr.id
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr.name
     *
     * @return the value of hr.name
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr.name
     *
     * @param name the value for hr.name
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr.phone
     *
     * @return the value of hr.phone
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr.phone
     *
     * @param phone the value for hr.phone
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr.telephone
     *
     * @return the value of hr.telephone
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr.telephone
     *
     * @param telephone the value for hr.telephone
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr.address
     *
     * @return the value of hr.address
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr.address
     *
     * @param address the value for hr.address
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr.enabled
     *
     * @param enabled the value for hr.enabled
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr.username
     *
     * @return the value of hr.username
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    public String getUsername() {
        return username;
    }

    @Override
    public boolean isAccountNonExpired() {
        return true;
    }

    @Override
    public boolean isAccountNonLocked() {
        return true;
    }

    @Override
    public boolean isCredentialsNonExpired() {
        return true;
    }

    @Override
    public boolean isEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr.username
     *
     * @param username the value for hr.username
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    @Override
    @JsonIgnore
    public Collection<? extends GrantedAuthority> getAuthorities() {
        List<SimpleGrantedAuthority> authorities = new ArrayList<>();
        for (Role role : roles) {
            authorities.add(new SimpleGrantedAuthority(role.getName()));
        }
        return authorities;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr.password
     *
     * @return the value of hr.password
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr.password
     *
     * @param password the value for hr.password
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr.userface
     *
     * @return the value of hr.userface
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    public String getUserface() {
        return userface;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr.userface
     *
     * @param userface the value for hr.userface
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    public void setUserface(String userface) {
        this.userface = userface == null ? null : userface.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr.remark
     *
     * @return the value of hr.remark
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr.remark
     *
     * @param remark the value for hr.remark
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}