package com.mmt.vhr.model;

import java.util.Date;

public class JOblevel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column joblevel.id
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column joblevel.name
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column joblevel.titleLevel
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    private String titleLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column joblevel.createDate
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column joblevel.enabled
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    private Boolean enabled;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column joblevel.id
     *
     * @return the value of joblevel.id
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column joblevel.id
     *
     * @param id the value for joblevel.id
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column joblevel.name
     *
     * @return the value of joblevel.name
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column joblevel.name
     *
     * @param name the value for joblevel.name
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column joblevel.titleLevel
     *
     * @return the value of joblevel.titleLevel
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    public String getTitleLevel() {
        return titleLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column joblevel.titleLevel
     *
     * @param titleLevel the value for joblevel.titleLevel
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    public void setTitleLevel(String titleLevel) {
        this.titleLevel = titleLevel == null ? null : titleLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column joblevel.createDate
     *
     * @return the value of joblevel.createDate
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column joblevel.createDate
     *
     * @param createDate the value for joblevel.createDate
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column joblevel.enabled
     *
     * @return the value of joblevel.enabled
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    public Boolean getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column joblevel.enabled
     *
     * @param enabled the value for joblevel.enabled
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }
}