package com.mmt.vhr.model;

public class SysMsg {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysmsg.id
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysmsg.mid
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    private Integer mid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysmsg.type
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysmsg.hrid
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    private Integer hrid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysmsg.state
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    private Integer state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysmsg.id
     *
     * @return the value of sysmsg.id
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysmsg.id
     *
     * @param id the value for sysmsg.id
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysmsg.mid
     *
     * @return the value of sysmsg.mid
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    public Integer getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysmsg.mid
     *
     * @param mid the value for sysmsg.mid
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    public void setMid(Integer mid) {
        this.mid = mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysmsg.type
     *
     * @return the value of sysmsg.type
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysmsg.type
     *
     * @param type the value for sysmsg.type
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysmsg.hrid
     *
     * @return the value of sysmsg.hrid
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    public Integer getHrid() {
        return hrid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysmsg.hrid
     *
     * @param hrid the value for sysmsg.hrid
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    public void setHrid(Integer hrid) {
        this.hrid = hrid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysmsg.state
     *
     * @return the value of sysmsg.state
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysmsg.state
     *
     * @param state the value for sysmsg.state
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    public void setState(Integer state) {
        this.state = state;
    }
}