package com.mmt.vhr.mapper;

import com.mmt.vhr.model.Adjustsalary;
import com.mmt.vhr.model.AdjustsalaryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AdjustsalaryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adjustsalary
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    long countByExample(AdjustsalaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adjustsalary
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    int deleteByExample(AdjustsalaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adjustsalary
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adjustsalary
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    int insert(Adjustsalary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adjustsalary
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    int insertSelective(Adjustsalary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adjustsalary
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    List<Adjustsalary> selectByExample(AdjustsalaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adjustsalary
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    Adjustsalary selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adjustsalary
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    int updateByExampleSelective(@Param("record") Adjustsalary record, @Param("example") AdjustsalaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adjustsalary
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    int updateByExample(@Param("record") Adjustsalary record, @Param("example") AdjustsalaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adjustsalary
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    int updateByPrimaryKeySelective(Adjustsalary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adjustsalary
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    int updateByPrimaryKey(Adjustsalary record);
}