package com.mmt.vhr.mapper;

import com.mmt.vhr.model.Appraise;
import com.mmt.vhr.model.AppraiseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AppraiseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appraise
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    long countByExample(AppraiseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appraise
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    int deleteByExample(AppraiseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appraise
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appraise
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    int insert(Appraise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appraise
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    int insertSelective(Appraise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appraise
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    List<Appraise> selectByExample(AppraiseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appraise
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    Appraise selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appraise
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    int updateByExampleSelective(@Param("record") Appraise record, @Param("example") AppraiseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appraise
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    int updateByExample(@Param("record") Appraise record, @Param("example") AppraiseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appraise
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    int updateByPrimaryKeySelective(Appraise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appraise
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    int updateByPrimaryKey(Appraise record);
}