package com.mmt.vhr.mapper;

import com.mmt.vhr.model.Employeeremove;
import com.mmt.vhr.model.EmployeeremoveExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EmployeeremoveMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeeremove
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    long countByExample(EmployeeremoveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeeremove
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    int deleteByExample(EmployeeremoveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeeremove
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeeremove
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    int insert(Employeeremove record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeeremove
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    int insertSelective(Employeeremove record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeeremove
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    List<Employeeremove> selectByExample(EmployeeremoveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeeremove
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    Employeeremove selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeeremove
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    int updateByExampleSelective(@Param("record") Employeeremove record, @Param("example") EmployeeremoveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeeremove
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    int updateByExample(@Param("record") Employeeremove record, @Param("example") EmployeeremoveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeeremove
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    int updateByPrimaryKeySelective(Employeeremove record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeeremove
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    int updateByPrimaryKey(Employeeremove record);
}