package com.mmt.vhr.mapper;

import com.mmt.vhr.model.Employeetrain;
import com.mmt.vhr.model.EmployeetrainExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EmployeetrainMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeetrain
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    long countByExample(EmployeetrainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeetrain
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    int deleteByExample(EmployeetrainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeetrain
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeetrain
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    int insert(Employeetrain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeetrain
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    int insertSelective(Employeetrain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeetrain
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    List<Employeetrain> selectByExample(EmployeetrainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeetrain
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    Employeetrain selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeetrain
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    int updateByExampleSelective(@Param("record") Employeetrain record, @Param("example") EmployeetrainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeetrain
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    int updateByExample(@Param("record") Employeetrain record, @Param("example") EmployeetrainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeetrain
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    int updateByPrimaryKeySelective(Employeetrain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeetrain
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    int updateByPrimaryKey(Employeetrain record);
}