package com.mmt.vhr.mapper;

import com.mmt.vhr.model.Empsalary;
import com.mmt.vhr.model.EmpsalaryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EmpsalaryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empsalary
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    long countByExample(EmpsalaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empsalary
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    int deleteByExample(EmpsalaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empsalary
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empsalary
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    int insert(Empsalary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empsalary
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    int insertSelective(Empsalary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empsalary
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    List<Empsalary> selectByExample(EmpsalaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empsalary
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    Empsalary selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empsalary
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    int updateByExampleSelective(@Param("record") Empsalary record, @Param("example") EmpsalaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empsalary
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    int updateByExample(@Param("record") Empsalary record, @Param("example") EmpsalaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empsalary
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    int updateByPrimaryKeySelective(Empsalary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empsalary
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    int updateByPrimaryKey(Empsalary record);
}