package com.mmt.vhr.mapper;

import com.mmt.vhr.model.MenuRole;
import com.mmt.vhr.model.MenuRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MenuRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_role
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    long countByExample(MenuRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_role
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    int deleteByExample(MenuRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_role
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_role
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    int insert(MenuRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_role
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    int insertSelective(MenuRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_role
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    List<MenuRole> selectByExample(MenuRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_role
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    MenuRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_role
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    int updateByExampleSelective(@Param("record") MenuRole record, @Param("example") MenuRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_role
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    int updateByExample(@Param("record") MenuRole record, @Param("example") MenuRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_role
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    int updateByPrimaryKeySelective(MenuRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_role
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    int updateByPrimaryKey(MenuRole record);
}