package com.mmt.vhr.mapper;

import com.mmt.vhr.model.MsgContent;
import com.mmt.vhr.model.MsgContentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MsgContentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msgcontent
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    long countByExample(MsgContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msgcontent
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    int deleteByExample(MsgContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msgcontent
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msgcontent
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    int insert(MsgContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msgcontent
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    int insertSelective(MsgContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msgcontent
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    List<MsgContent> selectByExample(MsgContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msgcontent
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    MsgContent selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msgcontent
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    int updateByExampleSelective(@Param("record") MsgContent record, @Param("example") MsgContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msgcontent
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    int updateByExample(@Param("record") MsgContent record, @Param("example") MsgContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msgcontent
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    int updateByPrimaryKeySelective(MsgContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msgcontent
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    int updateByPrimaryKey(MsgContent record);
}