package com.mmt.vhr.mapper;

import com.mmt.vhr.model.Politicsstatus;
import com.mmt.vhr.model.PoliticsstatusExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PoliticsstatusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table politicsstatus
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    long countByExample(PoliticsstatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table politicsstatus
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    int deleteByExample(PoliticsstatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table politicsstatus
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table politicsstatus
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    int insert(Politicsstatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table politicsstatus
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    int insertSelective(Politicsstatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table politicsstatus
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    List<Politicsstatus> selectByExample(PoliticsstatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table politicsstatus
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    Politicsstatus selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table politicsstatus
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    int updateByExampleSelective(@Param("record") Politicsstatus record, @Param("example") PoliticsstatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table politicsstatus
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    int updateByExample(@Param("record") Politicsstatus record, @Param("example") PoliticsstatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table politicsstatus
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    int updateByPrimaryKeySelective(Politicsstatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table politicsstatus
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    int updateByPrimaryKey(Politicsstatus record);
}