package com.mmt.vhr.mapper;

import com.mmt.vhr.model.SysMsg;
import com.mmt.vhr.model.SysMsgExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysMsgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmsg
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    long countByExample(SysMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmsg
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    int deleteByExample(SysMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmsg
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmsg
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    int insert(SysMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmsg
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    int insertSelective(SysMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmsg
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    List<SysMsg> selectByExample(SysMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmsg
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    SysMsg selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmsg
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    int updateByExampleSelective(@Param("record") SysMsg record, @Param("example") SysMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmsg
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    int updateByExample(@Param("record") SysMsg record, @Param("example") SysMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmsg
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    int updateByPrimaryKeySelective(SysMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmsg
     *
     * @mbg.generated Mon Mar 23 22:38:18 CST 2020
     */
    int updateByPrimaryKey(SysMsg record);
}